services:
  - type: web
    name: whatsapp-web
    env: node
    region: oregon
    buildCommand: |
      apt-get update
      apt-get install -y wget curl unzip fontconfig
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dpkg -i google-chrome-stable_current_amd64.deb || apt-get -fy install
      npm install
    startCommand: node server.js
    envVars:
      - key: CHROME_PATH
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: true
