services:
  - type: web
    name: whatsapp-web
    env: node
    region: oregon
    buildCommand: |
      curl -O https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dpkg -i google-chrome-stable_current_amd64.deb || apt-get -f install -y
      npm install
    startCommand: node server.js
    envVars:
      - key: CHROME_PATH
        value: /usr/bin/google-chrome
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
