services:
  - type: web
    name: whatsapp-web
    env: node
    region: oregon
    buildCommand: |
      apt-get update
      apt-get install -y chromium
      npm install
    startCommand: node server.js
    envVars:
      - key: CHROME_PATH
        value: /usr/bin/chromium
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: true
