services:
  - type: web
    name: whatsapp-web
    env: node
    region: oregon
    buildCommand: |
      curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee -a /etc/apt/sources.list.d/google-chrome.list
      apt-get update && apt-get install -y google-chrome-stable
      npm install
    startCommand: node server.js
    envVars:
      - key: CHROME_PATH
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: true
